-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.find_room_by_id(IN target_id uuid)
    RETURNS rooms
    LANGUAGE 'sql'
    VOLATILE SECURITY DEFINER
    PARALLEL UNSAFE
    COST 100
    
AS $BODY$
 SELECT * FROM public.rooms WHERE id = target_id LIMIT 1; 
$BODY$;
