-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.

CREATE OR REPLACE FUNCTION public.find_room_by_id(
	target_id uuid)
    RETURNS rooms
    LANGUAGE 'sql'
    COST 100
    VOLATILE SECURITY DEFINER PARALLEL UNSAFE
AS $BODY$
 SELECT * FROM public.rooms WHERE public.rooms.id = id LIMIT 1; 
$BODY$;

ALTER FUNCTION public.find_room_by_id(uuid)
    OWNER TO postgres;

GRANT EXECUTE ON FUNCTION public.find_room_by_id(uuid) TO PUBLIC;

GRANT EXECUTE ON FUNCTION public.find_room_by_id(uuid) TO anon;

GRANT EXECUTE ON FUNCTION public.find_room_by_id(uuid) TO authenticated;

GRANT EXECUTE ON FUNCTION public.find_room_by_id(uuid) TO postgres;

GRANT EXECUTE ON FUNCTION public.find_room_by_id(uuid) TO service_role;
