-- This script was generated by the Schema Diff utility in pgAdmin 4
-- For the circular dependencies, the order in which Schema Diff writes the objects is not very sophisticated
-- and may require manual changes to the script to ensure changes are applied in the correct order.
-- Please report an issue for any failure with the reproduction steps.
ALTER TABLE IF EXISTS public.room_message_queue
    ALTER COLUMN id DROP DEFAULT;
    
ALTER TABLE public.room_message_queue
    ALTER COLUMN id TYPE bigint USING 0; -- Assume no one had put this app in production

ALTER TABLE IF EXISTS public.room_message_queue
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 );

ALTER TABLE IF EXISTS public.room_message_queue
    ADD COLUMN dst_user_dev_id uuid NOT NULL;

ALTER TABLE IF EXISTS public.room_message_queue
    ADD COLUMN src_user_dev_id uuid NOT NULL;
